### PR TITLE
Cleanup from Rubocop suggestions

### LINKED ISSUE #13: Add Coveralls test coverage to README + PR process
Right now we capture this data but don't actually do anything with it.

### LINKED ISSUE #29: Add CodeClimate support
Codeclimate does a series of checks for code quality.  It would be nice to add code climate support so we can continue to improve the quality of this project.

### PR DESCRIPTION
**Pull request by natebird**
### Changes
* Use Ruby 1.9 syntax. `:foo => bar` to `foo: bar`.
* Cleanup code for consistency with Rubocop.
* Use single quotes where possible.
* Add code coverage badge to readme. fixes #13 
* Add CodeClimate maintainability badge to readme. fixes #29

### CODE REVIEW

**Comment by oniofchaos** [comment]
Let me know if you want any help with this

**Comment by natebird** [comment]
@oniofchaos - are you OK with moving to the ruby 1.9 syntax? i.e. `:foo => bar` to `foo: bar`.

**Comment by oniofchaos** [comment]
Yeah!

**Comment by natebird** [comment]
@oniofchaos This is ready for review. Perhaps we review PR [#26](https://github.com/devise-security/devise-security/pull/26) first and then I'll rebase this off of that PR. I'm guessing there will be a couple conflicts between the two PRs.

**Comment by oniofchaos** [comment]
This one looks ready now

**Comment by natebird** [comment]
Circle doesn't understand the separate gemfiles. I'm going to remove CircleCI for now.

**Comment by olbrich** [comment]
@natebird FYI... re setting up CircleCi to handle multiple gemfiles.   https://github.com/thoughtbot/appraisal#circle-ci-integration

While I like CircleCI, I think Travis does a better job of testing against the various combinations of dependencies.

**Pull request merged**
