### PR TITLE
Fix 'send' of 'path_for' on controller helpers

### PR DESCRIPTION
**Pull request by djpremier**
When a user has their password expired, a redirection to the new password form occurs. However, when this redirect happens from a location other than the User's scope, an error is raised informing that such method does not exist.

The solution is based on the implementation of Devise itself to send the redirect according to the scope's context.
https://github.com/heartcombo/devise/blob/main/lib/devise/controllers/url_helpers.rb#L50-L53

Error context:
```
NoMethodError: undefined method `user_password_expired_path' for #<App::NegotiationsController:0x00007fafdbc3f4f0>

devise-security/controllers/helpers.rb:91 in `change_password_required_path_for'
devise-security/controllers/helpers.rb:80 in `redirect_for_password_change'
devise-security/controllers/helpers.rb:53 in `block in handle_password_change'
devise-security/controllers/helpers.rb:48 in `any?'
devise-security/controllers/helpers.rb:48 in `handle_password_change'
active_support/callbacks.rb:426 in `block in make_lambda'
active_support/callbacks.rb:198 in `block (2 levels) in halting'
abstract_controller/callbacks.rb:34 in `block (2 levels) in <module:Callbacks>'
active_support/callbacks.rb:199 in `block in halting'
active_support/callbacks.rb:513 in `block in invoke_before'
active_support/callbacks.rb:513 in `each'
active_support/callbacks.rb:513 in `invoke_before'
active_support/callbacks.rb:107 in `block in run_callbacks'
active_support/callbacks.rb:136 in `run_callbacks'
abstract_controller/callbacks.rb:41 in `process_action'
action_controller/metal/rescue.rb:22 in `process_action'
action_controller/metal/instrumentation.rb:34 in `block in process_action'
active_support/notifications.rb:168 in `block in instrument'
active_support/notifications/instrumenter.rb:23 in `instrument'
active_support/notifications.rb:168 in `instrument'
action_controller/metal/instrumentation.rb:32 in `process_action'
action_controller/metal/params_wrapper.rb:256 in `process_action'
active_record/railties/controller_runtime.rb:24 in `process_action'
abstract_controller/base.rb:134 in `process'
action_view/rendering.rb:32 in `process'
action_controller/metal.rb:191 in `dispatch'
action_controller/metal.rb:252 in `dispatch'
action_dispatch/routing/route_set.rb:52 in `dispatch'
action_dispatch/routing/route_set.rb:34 in `serve'
action_dispatch/journey/router.rb:52 in `block in serve'
action_dispatch/journey/router.rb:35 in `each'
action_dispatch/journey/router.rb:35 in `serve'
action_dispatch/routing/route_set.rb:840 in `call'
rails/engine.rb:524 in `call'
rails/railtie.rb:190 in `public_send'
rails/railtie.rb:190 in `method_missing'
action_dispatch/routing/mapper.rb:19 in `block in <class:Constraints>'
action_dispatch/routing/mapper.rb:48 in `serve'
action_dispatch/journey/router.rb:52 in `block in serve'
action_dispatch/journey/router.rb:35 in `each'
action_dispatch/journey/router.rb:35 in `serve'
action_dispatch/routing/route_set.rb:840 in `call'
omniauth/strategy.rb:192 in `call!'
omniauth/strategy.rb:169 in `call'
omniauth/strategy.rb:192 in `call!'
omniauth/strategy.rb:169 in `call'
warden/manager.rb:36 in `block in call'
warden/manager.rb:34 in `catch'
warden/manager.rb:34 in `call'
rack/tempfile_reaper.rb:15 in `call'
rack/etag.rb:27 in `call'
rack/conditional_get.rb:27 in `call'
rack/head.rb:12 in `call'
action_dispatch/http/content_security_policy.rb:18 in `call'
rack/session/abstract/id.rb:266 in `context'
rack/session/abstract/id.rb:260 in `call'
action_dispatch/middleware/cookies.rb:670 in `call'
action_dispatch/middleware/callbacks.rb:28 in `block in call'
active_support/callbacks.rb:98 in `run_callbacks'
action_dispatch/middleware/callbacks.rb:26 in `call'
action_dispatch/middleware/debug_exceptions.rb:61 in `call'
action_dispatch/middleware/show_exceptions.rb:33 in `call'
rails/rack/logger.rb:38 in `call_app'
rails/rack/logger.rb:26 in `block in call'
active_support/tagged_logging.rb:71 in `block in tagged'
active_support/tagged_logging.rb:28 in `tagged'
active_support/tagged_logging.rb:71 in `tagged'
rails/rack/logger.rb:26 in `call'
action_dispatch/middleware/remote_ip.rb:81 in `call'
request_store/middleware.rb:19 in `call'
action_dispatch/middleware/request_id.rb:27 in `call'
rack/method_override.rb:24 in `call'
rack/runtime.rb:22 in `call'
active_support/cache/strategy/local_cache_middleware.rb:29 in `call'
action_dispatch/middleware/executor.rb:14 in `call'
action_dispatch/middleware/static.rb:127 in `call'
rack/sendfile.rb:110 in `call'
```

### CODE REVIEW

**Comment by djpremier** [comment]
As a complement, a similar case (which also occurs sometimes)
https://stackoverflow.com/questions/50116571/devise-security-gem-devise-controller-not-found-rails-5-2

**Comment by dillonwelch** [comment]
Code looks good - please add a test to ensure that the logic works correctly :)

**Comment by djpremier** [comment]
> Code looks good - please add a test to ensure that the logic works correctly :)

Hi Dillon, I tried but couldn't formulate a test to cover this case. Currently there are already two that cover the part of redirecting whether or not you are logged in, but somehow they don't get this error.

Do you have any tips on how I could be writing?

**Comment by dillonwelch** [comment]
My guess would be here https://github.com/devise-security/devise-security/blob/master/test/controllers/test_password_expired_controller.rb

I'd also recommend digging through the test suite of `devise` to see how they are testing the code you linked.

Note: I didn't originally write this project so I'm on a learning journey with you here :)

**Comment by piradata** [comment]
Was with the same problem here, will try to write some test for it if the time allows me

**Comment by piradata** [comment]
Was with the same problem here, will try to write some test for it if the time allows me

**Comment by dillonwelch** [comment]
Thank you!

**Pull request merged**
