### PR TITLE
Bump devise-security to 0.15.0

### PR DESCRIPTION
**Pull request by oniofchaos**

### CODE REVIEW

**Comment by oniofchaos** [comment]
@olbrich can I get a 👍 for releasing this version?

**Review by tmr08c — APPROVED** [review]
Since this is pre-1.0 it doesn't matter too much, but looking at the list of commits, nothing too crazy sticks out:

```
> git log --oneline v0.14.3..HEAD         

e66b1db Merge branch 'master' into version-bump
9b8aafa Reset default ruby-version for development to 2.5.8 (#259)
ce11948 Bump mongoid from 7.1.4 to 7.1.5 (#256)
adfd3ca Bump devise-security to 0.15.0
99ad9d1 Replace TravisCI with Github Actions (#252)
ad50cdb Add zh_TW translation (#244)
46f20dc Bump mongoid from 7.1.2 to 7.1.4 (#250)
02a209b Bump devise from 4.7.2 to 4.7.3 (#230)
8f38ba5 Fix spanish translations (#234)
b649037 Add Belarusian locale (#236)
5aa3bc7 Bump solargraph from 0.39.15 to 0.39.17 (#237)
c4508cb Add Czech (cs) locale (#242)
a0bd791 Bump default dev ruby to 2.7.1 (#249)
0140798 Reduce gem size (#248)
b773fdd Add Hindi (hi) locale (#241)
1c5f92d Allow random failures for unsupported Ruby/Rails pairs (#243)
e0d5f61 Add Simplified Chinese(zh_CN) locale (#235)
abe82ba Add fa locale (#240)
f2d3fe8 Add Ukrainian (UK) locale (#233)
32787de Update for Italian Translation (#229)
f83d59c Remove rails requirement (#219)
17fb920 Bump appraisal from 2.2.0 to 2.3.0 (#213)
f90c900 [Security] Bump rack from 2.2.2 to 2.2.3 (#215)
2869428 Bump minitest from 5.14.1 to 5.14.2 (#228)
cbfe281 Removed the warning message for double dependency in rails-controller-testing (#216)
5fa86c4 Add (Brazilian) Portuguese (PT) locale
42345e8 Bump solargraph from 0.39.14 to 0.39.15 (#227)
78afdb3 Bump solargraph from 0.39.8 to 0.39.14 (#225)
5312662 Bump pry-rescue from 1.5.1 to 1.5.2 (#217)
c467f0c Bump devise from 4.7.1 to 4.7.2 (#214)
6113522 password_expirable helper bugfix (#201)
bccc2c2 [Security] Bump websocket-extensions from 0.1.4 to 0.1.5 (#212)
421f15e Bump pry-rescue from 1.5.0 to 1.5.1 (#210)
ac9a5cb Bump solargraph from 0.39.7 to 0.39.8 (#211)
7cc56ed Formatting of helpers.rb and Gemfile (#209)
fc6ad54 Bump solargraph from 0.39.2 to 0.39.7 (#199)
00af261 Bump database_cleaner from 1.8.4 to 1.8.5 (#198)
5a20360 Bump minitest from 5.14.0 to 5.14.1 (#208)
35b359f Add Dutch (NL) locale (#196)
add810e Add minitest-rails in preparation for improving tests (#200)
d57b049 Bump solargraph from 0.39.0 to 0.39.2 (#194)
6c5a192 Bump rubocop-rails from 2.4.2 to 2.5.2 (#188)
55ae6b9 Bump solargraph from 0.38.6 to 0.39.0 (#192)
ec95a71 Allow API responses in PasswordExpiredController (#111)
1f18713 README improvements (#178)
264cb93 Update en.yml (#190)
8b2ce46 Updating a number of outdated dependencies (#187)
4b6e9a7 Drop ruby 2.4 support (#189)
726e4a5 Fixes/documentation for password complexity validator (#179)
af3b1a0 Fix attribute_changed? deprecation warning (#174)
0620f85 Bump database_cleaner from 1.8.2 to 1.8.3 (#169)
0f606dd Update rubocop requirement from ~> 0.75.0 to ~> 0.80.0 (#170)
393c645 Bump wwtd from 1.4.0 to 1.4.1 (#171)
8b6a9ab Bump database_cleaner from 1.7.0 to 1.8.2 (#167)
30af69b Bump solargraph from 0.38.4 to 0.38.5 (#165)
c75ca9c Bump rubocop-rails from 2.4.1 to 2.4.2 (#164)
e85e9b2 Bump solargraph from 0.38.3 to 0.38.4 (#163)
5b2db59 Bump solargraph from 0.38.2 to 0.38.3 (#162)
8661cc7 Updated dependencies (#161)
2030315 Update rubocop requirement from ~> 0.74.0 to ~> 0.75.0 (#140)
ad712ed Update travis build to support Rails 6 (#124)
4472c09 Bump devise from 4.7.0 to 4.7.1 (#131)
c671bfc Russian locale (#128)
404c0e2 Update rubocop requirement from ~> 0.71.0 to ~> 0.74.0 (#120)
44c731f Bump devise from 4.6.2 to 4.7.0 (#127)
2fd0e88 Bump wwtd from 1.3.0 to 1.4.0 (#125)
39d7c8a Use better german translation for symbol (#126)
bf3049b Add missing german translations (#123)
f53a97e [Security] Bump nokogiri from 1.10.3 to 1.10.4 (#121)
65ae052 Update dependencies (#118)
37b7201 Add ability to skip session limitable on a per record basis (#74)
7aa7d34 Merge pull request #117 from hiroki-sawano/fix-typo-in-ja-locale
3022f81 Merge branch 'master' into fix-typo-in-ja-locale
b54a7ac Merge pull request #115 from D-system/i18n-password-expire
185a632 Merge branch 'master' into i18n-password-expire
d5af846 Merge branch 'master' into fix-typo-in-ja-locale
54fb4ea Merge pull request #116 from devise-security/dependabot/bundler/rubocop-tw-0.73.0
f3a3fae Fix typo
cd69085 Update rubocop requirement from ~> 0.72.0 to ~> 0.73.0
e741b41 Paranoid verification: use I18n translation.
72e09f5 Password expired: use I18n translation.
8d57d1b Bump mongoid from 7.0.3 to 7.0.4 (#112)
711a580 Merge pull request #114 from devise-security/dependabot/bundler/rubocop-tw-0.72.0
d4be5dd Update rubocop requirement from ~> 0.66.0 to ~> 0.72.0
9fa60b8 [Security] Bump yard from 0.9.19 to 0.9.20 (#113)
68bfa6f check in Gemfile.lock (#109)
```

Mostly looks like dependency updates and new translations. I think the only breaking change I see is dropping 2.4 support, so we will want to call that out in the release notes.

**Comment by oniofchaos** [comment]
> Since this is pre-1.0 it doesn't matter too much, but looking at the list of commits, nothing too crazy sticks out:
> 
> ```
> > git log --oneline v0.14.3..HEAD         
> 
> e66b1db Merge branch 'master' into version-bump
> 9b8aafa Reset default ruby-version for development to 2.5.8 (#259)
> ce11948 Bump mongoid from 7.1.4 to 7.1.5 (#256)
> adfd3ca Bump devise-security to 0.15.0
> 99ad9d1 Replace TravisCI with Github Actions (#252)
> ad50cdb Add zh_TW translation (#244)
> 46f20dc Bump mongoid from 7.1.2 to 7.1.4 (#250)
> 02a209b Bump devise from 4.7.2 to 4.7.3 (#230)
> 8f38ba5 Fix spanish translations (#234)
> b649037 Add Belarusian locale (#236)
> 5aa3bc7 Bump solargraph from 0.39.15 to 0.39.17 (#237)
> c4508cb Add Czech (cs) locale (#242)
> a0bd791 Bump default dev ruby to 2.7.1 (#249)
> 0140798 Reduce gem size (#248)
> b773fdd Add Hindi (hi) locale (#241)
> 1c5f92d Allow random failures for unsupported Ruby/Rails pairs (#243)
> e0d5f61 Add Simplified Chinese(zh_CN) locale (#235)
> abe82ba Add fa locale (#240)
> f2d3fe8 Add Ukrainian (UK) locale (#233)
> 32787de Update for Italian Translation (#229)
> f83d59c Remove rails requirement (#219)
> 17fb920 Bump appraisal from 2.2.0 to 2.3.0 (#213)
> f90c900 [Security] Bump rack from 2.2.2 to 2.2.3 (#215)
> 2869428 Bump minitest from 5.14.1 to 5.14.2 (#228)
> cbfe281 Removed the warning message for double dependency in rails-controller-testing (#216)
> 5fa86c4 Add (Brazilian) Portuguese (PT) locale
> 42345e8 Bump solargraph from 0.39.14 to 0.39.15 (#227)
> 78afdb3 Bump solargraph from 0.39.8 to 0.39.14 (#225)
> 5312662 Bump pry-rescue from 1.5.1 to 1.5.2 (#217)
> c467f0c Bump devise from 4.7.1 to 4.7.2 (#214)
> 6113522 password_expirable helper bugfix (#201)
> bccc2c2 [Security] Bump websocket-extensions from 0.1.4 to 0.1.5 (#212)
> 421f15e Bump pry-rescue from 1.5.0 to 1.5.1 (#210)
> ac9a5cb Bump solargraph from 0.39.7 to 0.39.8 (#211)
> 7cc56ed Formatting of helpers.rb and Gemfile (#209)
> fc6ad54 Bump solargraph from 0.39.2 to 0.39.7 (#199)
> 00af261 Bump database_cleaner from 1.8.4 to 1.8.5 (#198)
> 5a20360 Bump minitest from 5.14.0 to 5.14.1 (#208)
> 35b359f Add Dutch (NL) locale (#196)
> add810e Add minitest-rails in preparation for improving tests (#200)
> d57b049 Bump solargraph from 0.39.0 to 0.39.2 (#194)
> 6c5a192 Bump rubocop-rails from 2.4.2 to 2.5.2 (#188)
> 55ae6b9 Bump solargraph from 0.38.6 to 0.39.0 (#192)
> ec95a71 Allow API responses in PasswordExpiredController (#111)
> 1f18713 README improvements (#178)
> 264cb93 Update en.yml (#190)
> 8b2ce46 Updating a number of outdated dependencies (#187)
> 4b6e9a7 Drop ruby 2.4 support (#189)
> 726e4a5 Fixes/documentation for password complexity validator (#179)
> af3b1a0 Fix attribute_changed? deprecation warning (#174)
> 0620f85 Bump database_cleaner from 1.8.2 to 1.8.3 (#169)
> 0f606dd Update rubocop requirement from ~> 0.75.0 to ~> 0.80.0 (#170)
> 393c645 Bump wwtd from 1.4.0 to 1.4.1 (#171)
> 8b6a9ab Bump database_cleaner from 1.7.0 to 1.8.2 (#167)
> 30af69b Bump solargraph from 0.38.4 to 0.38.5 (#165)
> c75ca9c Bump rubocop-rails from 2.4.1 to 2.4.2 (#164)
> e85e9b2 Bump solargraph from 0.38.3 to 0.38.4 (#163)
> 5b2db59 Bump solargraph from 0.38.2 to 0.38.3 (#162)
> 8661cc7 Updated dependencies (#161)
> 2030315 Update rubocop requirement from ~> 0.74.0 to ~> 0.75.0 (#140)
> ad712ed Update travis build to support Rails 6 (#124)
> 4472c09 Bump devise from 4.7.0 to 4.7.1 (#131)
> c671bfc Russian locale (#128)
> 404c0e2 Update rubocop requirement from ~> 0.71.0 to ~> 0.74.0 (#120)
> 44c731f Bump devise from 4.6.2 to 4.7.0 (#127)
> 2fd0e88 Bump wwtd from 1.3.0 to 1.4.0 (#125)
> 39d7c8a Use better german translation for symbol (#126)
> bf3049b Add missing german translations (#123)
> f53a97e [Security] Bump nokogiri from 1.10.3 to 1.10.4 (#121)
> 65ae052 Update dependencies (#118)
> 37b7201 Add ability to skip session limitable on a per record basis (#74)
> 7aa7d34 Merge pull request #117 from hiroki-sawano/fix-typo-in-ja-locale
> 3022f81 Merge branch 'master' into fix-typo-in-ja-locale
> b54a7ac Merge pull request #115 from D-system/i18n-password-expire
> 185a632 Merge branch 'master' into i18n-password-expire
> d5af846 Merge branch 'master' into fix-typo-in-ja-locale
> 54fb4ea Merge pull request #116 from devise-security/dependabot/bundler/rubocop-tw-0.73.0
> f3a3fae Fix typo
> cd69085 Update rubocop requirement from ~> 0.72.0 to ~> 0.73.0
> e741b41 Paranoid verification: use I18n translation.
> 72e09f5 Password expired: use I18n translation.
> 8d57d1b Bump mongoid from 7.0.3 to 7.0.4 (#112)
> 711a580 Merge pull request #114 from devise-security/dependabot/bundler/rubocop-tw-0.72.0
> d4be5dd Update rubocop requirement from ~> 0.66.0 to ~> 0.72.0
> 9fa60b8 [Security] Bump yard from 0.9.19 to 0.9.20 (#113)
> 68bfa6f check in Gemfile.lock (#109)
> ```
> 
> Mostly looks like dependency updates and new translations. I think the only breaking change I see is dropping 2.4 support, so we will want to call that out in the release notes. @olbrich should we add that as a note to the [release notes](https://github.com/devise-security/devise-security/releases/tag/untagged-c8098ae99a599dbaf7a5)?

Good catch! I will update the notes.

**Comment by oniofchaos** [comment]
Created https://github.com/devise-security/devise-security/pull/261 so that people can only update if they are using one of our supported versions 😄

**Comment by olbrich** [comment]
I don't think we should merge this until we have completed all the items in the 0.15 milestone or at least moved them to a future milestone if the appropriate branches aren't merged.

**Comment by oniofchaos** [comment]
I don't see anything critical in the milestone - how do you feel about moving them to 0.16?

**Pull request merged**
