### PR TITLE
Fix attribute_changed? deprecation warning

### PR DESCRIPTION
**Pull request by taylor-au**
Fix attribute_changed? deprecation warning

### CODE REVIEW

**Comment by oniofchaos** [comment]
@taylor-au why did you close?

**Comment by taylor-au** [comment]
@oniofchaos I was thinking that it would be a trivial code change to remove the deprecation warning, but it looks like it may require a Ruby upgrade and I don't have the time to invest in fixing this at the moment.

**Comment by oniofchaos** [comment]
No problem!

**Comment by oniofchaos** [comment]
BTW a thought - you can do something like
```ruby
if (defined?(:will_save_change_to_encrypted_password?) && will_save_change_to_encrypted_password?) ...
end
```
and that should handle older versions ruby

**Pull request closed without merging**
